### ISSUE TITLE
Tripleobject.initialize should return a copy of the initialized object

### ISSUE THREAD

**Issue by M3gar00** [coronado-fi/coronado#222]
I'm using Coronado to interface with the Triple API, and it works as long as the object is a top-level citizen (eg:
```
from coronado.merchant import Merchant

Merchant.initialize(BASE_URL, SERVICE_PATH, coronado_auth())
```
The issue is that this causes the `TripleObject.initalize` method to call AWS to attempt to retrieve client credentials before anything is mocked out in unit tests.

A solution I have used in the past to avoid this exact scenario is to wrap the offending top-level command in a function.
```
def _coronado_merchant() -> Merchant:
    return Merchant.initialize(BASE_URL, SERVICE_PATH, coronado_auth())
```
But `TripleObject.initialize` returns a None, instead of a copy of the initialized object. This means, when I run the code I get the following error:
```
File "/var/task/my_filename/", line ###, in my_function
    if merchant := _coronado_merchant().list(externalMerchantID=merchant_external_id):
AttributeError: 'NoneType' object has no attribute 'list
```

If `TripleObject.initialize` were to return a copy of the initialized object, I would be able to patch out the call to the external API (In this case an AWS data store), and run unit tests.

This is causing friction in that I cannot effectively mock calls to external data sources effectively. The reason is that `pytest` loads in the files to be tested (which initializes top-level commands, including calls to AWS data stores), then it runs its own code (including any patches to mock out calls to external API's).

**Comment by jon-laf-nexient-numo** [comment]
It feels like an anti-pattern that an initialization class method would return **None** and breaks the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). Barmar points out some good reasons in his [comments](https://stackoverflow.com/q/61806609) why this shouldn't be done.

**Comment by pr3d4t0r** [comment]
**Bzzzz**

This reply is based on the proposed (non-)solution to the "problem" - check this out:

```python
from coronado import TripleObject
from coronado.auth import Auth
from coronado.config import loadConfig
from coronado.merchant import Merchant
from coronado.merchant import SERVICE_PATH

conf = loadConfig()
a = Auth(conf['tokenURL'], conf['clientID'], conf['secret'])
```

## What's being initialized here?

```python
obj = Merchant.initialize(conf['serviceURL'], SERVICE_PATH, a)
```
Let's have a look...
```python
isinstance(obj, Merchant)
False

isinstance(obj, TripleObject)
False

isinstance(obj, type)
True
```

## Explanation

The first clue about what's happening appears here:
https://coronado-fi.github.io/coronado/coronado.html#TripleObject.initialize

`Merchant.initialize(args)` initializes the **class** so that it may interact with the Triple API to manipulate objects.  It doesn't initialize _**instances**_ of `Merchant`.  That's also why this isn't the anti-pattern.  The equivalent example that Jon described corresponds to a constructor or a factory method, which produce **an instance**, returning `None`.  That doesn't apply here.

`Merchant.initialize(args)` doesn't return anything because **the caller already has an instance of the `Merchant` class**.  And there is only one instance of the class in scope of the current Python run-time.  If the method were to return anything, it would be an instance of **class Merchant**, not an instance of **Merchant**.

Explanation in code:

```python
obj == Merchant
True

not isinstance(obj, Merchant)
True 
```
I'll check with you guys soon about addressing the problem, which is external to Coronado.  We could facilitate some kind of check "is the service up yet?" or something, but what you proposed won't solve the external problem of getting the service up.

**Comment by jon-laf-nexient-numo** [comment]
Thanks for the nice explanation, @ciurana-numo. Makes complete sense!

**Comment by pr3d4t0r** [comment]
## Mocking TripleObjects

All concrete Triple classes can be instantiated without arguments and they'll take default values as defined in the Triple API web services specification.  You can call them with:

```python
merchant = Merchant()
account = CardAccount()
# and so on
```
Without having to call `ConcreteClassName.initialize(args)` - this is only needed if you want to talk to the Triple API defined in the service URL through configuration.

Another way of doing this, if you want to test specific object values, is to instantiate new objects using JSON dictionaries with the required payload:

```python
 merchant = Merchant( { 
     'address': MOCK_ADDRESS.asSnakeCaseDictionary(),
     'assumed_name': 'Some Company',
     .
     .
 })
```
Per the Triple API and Coronado specs, the dictionary you pass must be in snake_case because the first class object is created from a JSON response from the Triple API, and those were implemented with snake_case.
